upstreamProjects:
  Mule-runtime/metadata-model-api/master
# Comment public setting to get oldMuleArtifact from private repo till we move them to the public Repo
# Uncomment it after they are copied
#mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11