upstreamProjects:
  Mule-runtime/metadata-model-api/master-MAY-2022
# Comment public setting to get oldMuleArtifact from private repo till we move them to the public Repo
# Uncomment it after they are copied
#mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
